### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by agonopol** [jklughammer/RefFreeDMA#1]
Hi 
I wanted to try RefFreeDMA for a school project, and I am wondering if you have any sample data that I can quickly try using? I wanted to try playing around and tweaking the algorithms to see if I can get any results.

**Comment by jklughammer** [comment]
Hi, glad you'd like to try RefFreeDMA. Please follow the "Quick start" instructions to test RefFreeDMA, Step 2 of the "7 steps to test RefFreeDMA" is where you download a small, downsampled data set, the analysis of which completes quickly and which is therefore ideal for testing. If you are looking for complete data sets, you can for example use the data described in our publication (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4695333/) which are available from GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE74026). But you can also use any other published RRBS data.

**Comment by agonopol** [comment]
Thanks! I was looking around the repo and didn't see it but I'll digg deeper into the Quick Start.
I'll let know of any findings or improvements that I can think of
