### ISSUE TITLE
RRBS_biseq_statistics columns meaning

### ISSUE THREAD

**Issue by srialle** [jklughammer/RefFreeDMA#3]
Dear Johanna,

I managed to run RefFreeDMA on my samples, and now I am trying to understand the results. In particular, the file RRBS_biseq_statistics.txt (produced in toSelf_filtered_0.08mm_final_concat) seems very informative, but I am not sure to understand every column. Can you please explain further their meaning? For example, what are the informative reads? Are they those who could be mapped to the deduced genome? Or, what is the adjustment made to obtain the globalMethylationMean_conversionAdjusted rate? How is computed the globalMethylationMean, and what is the diffrence with the readMethylationMean? Etc.
I really would like to fully understand those indicators in order to be able to explain their meaning to the biologist in charge of the project.

Many thanks in advance.

Best regards,

Stéphanie

**Comment by jklughammer** [comment]
Hi Stéphanie,
you can find a header egend for this output within the script that produces it - this link shoud take you to it: https://github.com/jklughammer/RefFreeDMA/blob/8cfcf83464e6d25e0f7c29e22bb6d7679c2801f3/scripts/biseqMethCalling.py#L2081

However, this output is super comprehensive and in practice you don't need that level of detail.
I would recommend you run the parse_stats.sh script (https://github.com/jklughammer/RefFreeDMA/blob/master/scripts/parse_stats.sh). This will produce more relevant summary statistic that includes the relevant information from the script you looked at already + other relevant info. Some of those headers might be self-explanatory, but I will post an explanation in the README in the next few days and also link it here. 

Best, Johanna

**Comment by srialle** [comment]
Thank you very much for the link to the header legend, it is exactly what I was looking for.

Thank you also for reminding me to run the parse_stats.sh script, I had forgotten to do it, and indeed it produces interesting statistics.

I have another question, regarding the interpretation of the results this time. The number of fragments I obtain is 784,577 (fragments_ref), but the number of uncovered fragments is very high (68 to 74% according to my samples. Do you think that something went wrong or is it usual to get this kind of rates?

Best,

Stéphanie

**Comment by jklughammer** [comment]
These numbers are indeed a bit towards the higher end. I frequently observe rates around 50-60%. As long as your mapping rates are good (~70% or higher) a problem with the deduced reference is unlikely. You can also check out this plot  `toSelf_filtered_0.08mm_final_concat/diffMeth_cpg/YOURSPECIES_overlap_stats.pdf`  which tells you the number of common CpGs measured between all pairs of samples. If you observe clusters or strong outliers, it might indicate that your samples have considerable variation in their DNA sequence (in the extreme, this might indicate different species).

**Comment by srialle** [comment]
The mapping rates are good indeed (93 to 95%). I just had a look to _overlap_stats.pdf and I see that ovelaps vary from 1 160 000 to 1 190 000 (I only have 3 samples so it is hard to see clusters), knowing that the number of "coveredCpGs" (in summary.txt file) vary from 1 339 786 to 1 593 735, so it seems good to me.  Am I wrong? Unless the overlap must be compared to the total CpG_measurements (which vary from 109 to 170 millions)...
I don't really understand how it is possible to have uncovered fragments, when the ref have been built by the very same reads. Except as you have said if the fragments are built from very different samples.

**Comment by jklughammer** [comment]
Ok, those numbers are very good! You compared to the correct column ("coveredCpGs").
Since your number of deduced reference fragments (784,577) is rather towards the lower end (I frequently observe >1M) and your mapping rates and overlaps are good, I don't think the relatively high rate of uncovered fragments is concerning. 
In the default setting RefFreeDMA only requires the presence of a sequence in 2 out of 4 samples (3 samples in your case) in order to be considered for the deduced reference. Therefore it is possible that a sequence is not present in one of the samples, and would then count toward "uncovered" in that sample (this is a sample specific measure, i.e. it doesn't mean that that fragment is uncovered in ALL samples).

**Comment by srialle** [comment]
Ok I understand. Thank you very much for your help!
Best,
Stéphanie

**Comment by jklughammer** [comment]
Readme is now updated: https://github.com/jklughammer/RefFreeDMA/blob/master/README.md#output-statistics
Best, Johanna

**Comment by srialle** [comment]
Many thanks!
Best,
Stephanie
